# Generated by Django 4.0.5 on 2022-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_notebook_date_of_completion_notebook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='status',
            field=models.IntegerField(choices=[(1, 'выполнено'), (2, 'выполняется')], default=1),
        ),
    ]
