# Generated by Django 4.0.5 on 2022-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_notebook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='header',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='status',
            field=models.IntegerField(choices=[(1, 'выполнено'), (0, 'выполняется')], default=1),
        ),
    ]
