# Generated by Django 4.0.5 on 2022-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_alter_notebook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='date_of_completion',
            field=models.DateField(auto_now=True),
        ),
    ]
